example/babel.config.js, example/ios/Podfile.lock, example/package.json, example/src/App.tsx, example/src/Examples/Basic.tsx, example/src/Examples/Compose.tsx, example/src/Examples/Icon.tsx, example/src/assets/close.svg, example/src/assets/index.ts, example/src/assets/send.svg, example/src/index.d.ts, src/RichText/Toolbar/Toolbar.tsx, src/RichText/Toolbar/actions.ts, src/RichText/useNativeEditor.tsx, yarn.lock
Todo - would like to add custom toolbar
=> Add Compose Example

example/src/Examples/Basic.tsx, example/src/Examples/DarkEditor.tsx, src/RichText/RichText.tsx, src/RichText/index.ts, src/RichText/theme.ts, src/bridges/core.ts, src/index.tsx, src/types/Theme.ts, website/docs/api/EditorBridge.md, website/docs/examples/basic.md, website/docs/examples/customTheme.md, website/docs/examples/darkTheme.md, website/docs/intro.md, website/sidebars.ts, website/src/css/custom.css
- Update doc colors
- Fix quote on dark mode
- Update theme API
- Export `images`
- Update docs
- Add blur
=> Small Fixes

src/TenTapViewNativeComponent.ts, website/docs/intro.md
Fix simple usage for expo without custom dev client
=> fix: expo simple usage

example/src/Examples/ConfigureExtentions.tsx, src/index.tsx
Dropcursor bridge was not being exported  #79
=> fix: export dropcursor

README.md, website/docs/intro.md
Fix broken link
Add toolbar to front readme
=> fix: update docs

website/docs/setup/advancedSetup.md
Add setup suggest by @mandrade2 in #80
=> Add Alternative Advanced Setup to Docs

src/RichText/Toolbar/Toolbar.tsx
=> fix: iconActive, iconDisabled

example/src/Examples/Basic.tsx, package.json, src/bridges/StarterKit.ts, src/bridges/br.ts, src/index.tsx, src/types/Actions.ts, src/webEditorUtils/index.ts, yarn.lock
GitHub doesnt let me upload a video example so here you go on [youtube](https://youtu.be/7aPtZiBsyXw)
closes: #107
=> fix: add br to starter kit

src/RichText/RichText.tsx, src/RichText/utils.ts
Fix unexpected EOF being thrown with some types of initial content
Fixed by trimming new lines before being injected
=> fix: initial content bug

src/RichText/RichText.tsx, src/RichText/useEditorBridge.tsx, src/RichText/utils.ts, website/docs/api/useEditorBridge.md
https://github.com/10play/10tap-editor/issues/122
JSON format:
HTML format:
Plain text format:
=> initialContent JSON value support

.github/workflows/cd.yml, .github/workflows/deploy.yml
Dont deploy web/npm in case there is no relevant change
=> fix: cd run only when change on lib or web

.github/workflows/cd.yml, src/RichText/useEditorBridge.tsx, website/docs/examples/search.md, website/docs/setup/advancedSetup.md, website/sidebars.ts
Added search example to website + trigger deploy for Utils fix (#150)
=> Add search example and trigger CD

website/docs/api/EditorBridge.md
=> docs: update EditorBridge.md

website/docs/setup/installation.md
https://github.com/10play/10tap-editor/issues/177
=> docs: min android api version

src/RichText/useEditorBridge.tsx, src/RichText/utils.ts, src/types/EditorBridge.ts, src/webEditorUtils/useTenTap.tsx, website/docs/api/useEditorBridge.md
https://github.com/10play/10tap-editor/issues/184#issuecomment-2304826219
=> fix: android selection is bad 184

README.md, website/docs/setup/expoWeb.md, website/docs/setup/installation.md, website/sidebars.ts
Add docs for expo-web support (metro + webpack) #84
https://github.com/user-attachments/assets/f80df30a-1efe-44c9-bc38-8f5d99ba8825
=> expo-web support

website/docs/examples/comments.md
=> docs: comments demo

src/RichText/Toolbar/Toolbar.tsx
=> fix: link on web

example/ios/Podfile.lock, package.json, yarn.lock
This PR upgrade tiptap link extension to `2.10.3` it looks like it solve #233
=> Upgrade tiptap link extension

src/webEditorUtils/useTenTap.tsx
Should fix issue on https://github.com/10play/10tap-editor/issues/244
https://github.com/user-attachments/assets/9cf7536a-00fc-4436-a681-ad3fc9d3ce70
https://github.com/user-attachments/assets/5b562b6b-8963-412e-a611-891e7f9e8a28
=> fix: dynamic jitter ios + android

src/RichText/Toolbar/Toolbar.tsx, src/RichText/Toolbar/actions.ts
This PR should fix the issue described in  #270
=> Fix: remove circular imports

src/RichText/useEditorBridge.tsx
Potential fix for https://github.com/10play/10tap-editor/issues/175
=> Fix Editor Not Ready Warning

README.md
https://github.com/10play/10tap-editor/issues/293
=> modify: usage code
