10play/10tap-editor

example/src/Examples/CustomCss.tsx, src/RichText/RichText.tsx, src/RichText/useEditorBridge.tsx, src/RichText/utils.ts, src/bridges/base.ts, src/bridges/core.ts, website/docs/api/EditorBridge.md, website/docs/examples/customCss.md
#57 This pr adds a way to dynamically add css with `injectCSS`
Each BridgeExtension now creates it's own stylesheet on the webview with a `tag` equivalent to it's name.
The `injectCSS` function receives css and a tag, it then creates or updates the stylesheet with the given tag dynamically. This gives us the option to update a Bridge's css dynamically, or to add stylesheets unrelated to any bridge with a custom tag. 
https://github.com/10play/10tap-editor/assets/36531255/24191e6c-d1fb-4b9f-ba8c-cc7eb6e56d6a
=> Add `injectCSS` for Dynamic CSS

example/src/Examples/ConfigureExtentions.tsx, package.json, src/bridges/StarterKit.ts, src/bridges/dropcursor.ts, website/docs/api/BridgeExtensions.md, yarn.lock
Add support for https://tiptap.dev/docs/editor/api/extensions/dropcursor#settings #65 
Not to much in this bridge, as no messaging is needed, only thing exposed is configure which can be used with `configureExtension`
```tsx
DropCursorBridge.configureExtension({
color: '#84affe',
width: 2,
}),
```
https://github.com/10play/10tap-editor/assets/36531255/3c9a1d37-fada-4fb2-807c-c30ae62b078d
=> Add Basic DropCursor Support

example/src/Examples/WithKeyboard.tsx, src/RichText/Keyboard/ColorKeyboard.tsx, src/RichText/Keyboard/keyboardTheme.ts, src/RichText/useEditorBridge.tsx, src/types/Theme.ts, src/utils/mergeThemes.ts, website/docs/examples/customTheme.md
Fix a bug where default colors are added to color keyboard even when overridden, and add a way to use attributes instead of a actual colors. #68
=> Color Keyboard Pallete Override 

package.json
Fix issue where codegen fails to find tentap, because 
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" 
```
https://github.com/10play/10tap-editor/issues/82
=> Fix Codegen Issue with RN 0.73.5+

src/RichText/RichText.tsx, src/RichText/useEditorBridge.tsx, src/bridges/core.ts, src/types/EditorBridge.ts, src/webEditorUtils/useTenTap.tsx, website/docs/api/BridgeState.md, website/docs/api/EditorBridge.md, website/docs/api/useEditorBridge.md
Add `editable` prop to `useEditorBridge`, in addition add `setEditable` to core extension. #93
By default editable is set to true
https://github.com/10play/10tap-editor/assets/36531255/b5701572-2b56-4248-94b8-53f5d73be5f1
=> Add Editable Prop

example/ios/Podfile.lock, src/RichText/Toolbar/actions.ts, src/bridges/tasklist.ts
Set `nested: true` by default on task list item extension. I think ideally we should add a way to configure extension dependancies, but for now this might be enough.
https://github.com/10play/10tap-editor/assets/36531255/db0cd26b-7e62-4dff-aa2a-496cc4dae8b2
Need to test expo, to make sure configure in bridge does not cause any problems
=> Lift/Sink Task List Item

src/RichText/RichText.tsx, src/bridges/core.ts
1/10 times the editor autofocus not working on android, I added a really hacky fix (adding 100ms timeout before requestfocus) for it as detailed here:
https://github.com/react-native-webview/react-native-webview/issues/1172
In top of the TextInput hack for open the keyboard
I also use avoidIosKeyboard for android as well so when not true (mostly when using the editor not with fullsize) we wouldnt add bottom padding, we will change `avoidIosKeyboard` -> `avoidKeyboard` in v1.0.0
=> Fix android focus and dynamic height

src/webEditorUtils/vite.config.ts
When using advanced setup and trying to work with decorations we see that error:
```
undefined is not an object (evaluating 'this.members[i].localsInner')
```
After a lot of investigations it looks like rollup/vite might bundle prosemirror-view inside the web-utils bundle what can cause double instances of prosemirror-view, thanks to:
https://github.com/ueberdosis/tiptap/issues/3869#issuecomment-2167931620
I managed to external @tiptap/pm/view from web-utils and it solve the issues with decorations
=> fix: issue with decorations on advanced setup

example/src/Examples/Advanced/editor-web/index.tsx, src/RichText/utils.ts, src/simpleWebEditor/index.tsx, src/webEditorUtils/useTenTap.tsx, website/docs/setup/advancedSetup.md
Fix for: https://github.com/10play/10tap-editor/issues/133
On android - react-native-webview there is a bug where sometimes the content is injected https://github.com/react-native-webview/react-native-webview/pull/2960
To overcome this we will check if the content is injected before rendering the editor
=> fix: android crash on first mount

ios/TenTapViewImpl.mm
Continuing on #150 , i recently update the app to version `0.5.11`. but i notice there is an import left behind on `TentapUtils.h` at `TenTapViewImpl.mm`. please re-check.
```
The following build commands failed:
CompileC /Users/user/Library/Developer/Xcode/DerivedData/Project-dngdlqbebhvoynewnrxrduhaytpb/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/tentap.build/Objects-normal/arm64/TenTapViewImpl.o /Users/user/Workspaces/Project/project/node_modules/@10play/tentap-editor/ios/TenTapViewImpl.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'tentap' from project 'Pods')
(1 failure)
```
=> fix: rename TentapUtils.h call on TenTapViewImpl

package.json, src/RichText/Toolbar/EditLinkBar.tsx
Link bar link button container has active styling but the icon itself lacked the active styling. 
This PR adds the active styling to the link button in `EditLinkBar.tsx`
=> fix: add active styling to edit link bar link icon

src/webEditorUtils/vite.config.ts
Fix for https://github.com/10play/10tap-editor/issues/167
Remove `@tiptap/pm/view` from external - seems to be causing issues with the pro mentions example
This was added to fix some prosemirror decoration issues, we'll need to find a new way to solve that https://github.com/ueberdosis/tiptap/issues/3869#issuecomment-2167931620
=> fix: vite config for web editor utils

src/RichText/theme.ts, src/bridges/HighlightSelection.ts, src/simpleWebEditor/index.html
We added on iOS `HighlightSelection.ts` so when the user edit link and the editor is not on focus anymore he still be aware to his selection,
1.
2.
The problem is that in dark mode we keep the same light blue which causes the selection to be unreadable:
Related issues:
https://github.com/10play/10tap-editor/issues/180
https://github.com/10play/10tap-editor/issues/166
https://github.com/10play/10tap-editor/issues/144
=> fix: override highlight selection background on darkmode

example/src/Examples/ConfigureExtentions.tsx, src/bridges/placeholder.ts, website/docs/api/EditorBridge.md
This PR adding the ability to change placeholder on runtime, took inspiration from:
https://github.com/ueberdosis/tiptap/issues/1044#issuecomment-2115619474
=> set placeholder on the fly

example/src/Examples/Advanced/editor-web/index.html, src/simpleWebEditor/index.html, website/docs/setup/advancedSetup.md
Add meta tag to disable use scale - this fixes an issue where focusing the editor causes text to seem bigger #222
=> fix: ios double click zoom

src/RichText/utils.ts, src/webEditorUtils/useTenTap.tsx
Fix jitter mentioned in https://github.com/10play/10tap-editor/issues/236 by adding paragraph height to total added height
=> fix: dynamic height jitter android

src/bridges/core.ts, website/docs/api/EditorBridge.md
Fix setContent typing to accept JSONContent as requested here https://github.com/10play/10tap-editor/issues/230
=> Fix setContent typing to accept JSONContent

src/webEditorUtils/useTenTap.tsx
As observed in https://github.com/10play/10tap-editor/blob/fca4b93169955c76fd028710076d30c25270935d/src/simpleWebEditor/index.tsx#L11-L16, there is a bug where sometimes the content is injected after the window is loaded on Android.
Although a `setInterval` check for `contentInjected` exists in `simpleWebEditor/index.tsx`, the problem arises because `window.initialContent` is evaluated immediately inside `useTenTap.tsx`. This causes `initialContent` to resolve to an empty string when the content injection occurs post-window load.
This PR modifies the `useTenTap` hook to evaluate `window.initialContent` inside the hook, ensuring content is set properly, even if it is injected later.
=> Fix `initialContent` not working consistently on Android

src/RichText/RichText.tsx, website/docs/api/Components.md
The current behaviour we have here is that if you pass your own onMessage handler, it will override the existing TenTap one, which is, I think, not the intended behaviour in most cases. 
Therefore I just introduced another prop that makes this possible, while maintaining the original behaviour. Basically, if you use onMessage right now through tentap, and you upgrade to this version, nothing changes.
=> Let onMessage handlers coexist

src/bridges/core.ts, website/docs/api/BridgeState.md
Previously there was no way to tell, from the RN side, if the editor is empty or not. With this change we can now do things such as enable/disable the submit button based on if the editor is empty.
Example:
```tsx
function MyComponent() {
const editor = useEditorBridge(...);
const editorState = useBridgeState(editor);
return (
<View>
...
<Button disabled={editorState.empty}>Submit</Button>
</View>
);
}
```
=> feat: add "empty" boolean to bridge state

package.json
- Fix deprecation warning by adding missing `ios.componentProvider` [configuration](https://reactnative.dev/docs/the-new-architecture/using-codegen#configuring-codegen).
- When using `@10play/tentap-editor`, the following deprecation warning appears:
```
[DEPRECATED] @10play/tentap-editor should add the 'ios.componentProvider' property in their codegenConfig
```
This maps the JavaScript TenTapView component to the iOS native TenTapView class for proper codegen support.
- react-native v0.79.2, expo sdk 53
- Verified warning no longer appears
=> fix: add ios.componentProvider to codegenConfig
